# Generated by Django 5.2.4 on 2025-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('assignment', 'Assignment'), ('report', 'Report')], max_length=20),
        ),
    ]
